from typing import ClassVar, Literal
from enum import Enum, unique

from pydantic import Field

from SkiNet.ML.configs.data_configs.base_data_config import BaseDataConfig
from SkiNet.Utils.csv_headers import (DATAPATH_HEADER, DATATYPE_HEADER, ISIC2017_MELANOMA_HEADER,
                                      ISIC2017_PREDEFINED_SPLIT_HEADER, ISIC2017_SEBORRHEIC_KERATOSIS_HEADER,
                                      SAMPLEID_HEADER)
from SkiNet.Utils.experiment_keys import DatasetKey
from SkiNet.Utils.project_paths import ISIC2017_CSV_NAME
from SkiNet.Utils.data.split_data import SplitConfig


@unique
class ISIC2017StratificationOptions(str, Enum):
    """
    Enum for ISIC 2017 dataset stratification options.
    These are the possible values for the "stratify_by" argument in the split_segmentation_metadata function
    for the ISIC 2017 dataset, which is used to specify the column by which to stratify the data
    for train/val/test sets.
    """
    ISIC2017_MELANOMA = ISIC2017_MELANOMA_HEADER
    ISIC2017_SEBORRHEIC_KERATOSIS = ISIC2017_SEBORRHEIC_KERATOSIS_HEADER


class ISIC2017DatasetConfig(BaseDataConfig):
    """
    Configuration for the ISIC 2017 dataset.

    :attributes:
        REQUIRED_COLUMNS (ClassVar[frozenset[str]]): Set of required columns in the metadata CSV.
        DATASET_KEY (ClassVar[DatasetKey]): Key for the Azure dataset.
        METADATA_CSV_NAME (ClassVar[str]): Name of the metadata CSV file as defined in project paths.

    The metadata CSV is expected to have been generated by ISIC2017LocalCSVBuilder or
    ISIC2017AzureCSVBuilder and must contain at minimum the sampleid, datapath, datatype,
    melanoma, and seborrheic_keratosis columns, plus a predefined_split column that records
    the original ISIC 2017 challenge split for each sample.

    Example usage for a local dataset:
    ```
    cfg = ISIC2017DatasetConfig(local_data_root="local_path/ISIC2017Data", azure_data=False)
    df = cfg.metadata
    ```

    Example usage for an Azure dataset:
    ```
    cfg = ISIC2017DatasetConfig(azure_blob_mount_point="mnt/data", azure_data=True)
    df = cfg.metadata
    ```
    """
    kind: Literal["isic2017"] = Field("isic2017", description="Dataset kind identifier for config selection and validation.")
    predefined_split_column: str | None = Field(
        default=ISIC2017_PREDEFINED_SPLIT_HEADER,
        description="Use the official ISIC 2017 challenge splits recorded in this column. "
                    "Set to None to fall back to a random split via split_train_size/val/test.",
    )
    split_stratify_column: ISIC2017StratificationOptions | None = Field(
        default=ISIC2017StratificationOptions.ISIC2017_MELANOMA,
        description="Column name in the metadata CSV to use for stratified splitting into train/val/test splits. "
        "Should be a column that exists in the metadata CSV and contains categorical labels for stratification. "
        "Set to None to disable stratification. For ISIC 2017, we use ISIC2017StratificationOptions for stratification."
    )

    REQUIRED_COLUMNS: ClassVar[frozenset[str]] = frozenset({SAMPLEID_HEADER, DATAPATH_HEADER, DATATYPE_HEADER})
    DATASET_KEY: ClassVar[DatasetKey] = DatasetKey.ISIC2017
    METADATA_CSV_NAME: ClassVar[str] = ISIC2017_CSV_NAME

    def get_split_config(self) -> SplitConfig:
        """
        Gets the SplitConfig for the ISIC 2017 dataset based on the specific split column and
        the train/val/test sizes and random seed defined in the BaseDataConfig.

        :returns: SplitConfig for the ISIC 2017 dataset, where the stratify_column is ISIC2017-specific when enabled.
        """
        return SplitConfig(
            train_size=self.split_train_size,
            val_size=self.split_val_size,
            test_size=self.split_test_size,
            stratify_column=self.split_stratify_column.value if self.split_stratify_column is not None else None,
            random_seed=self.split_random_seed,
        )
