# this is a file to make an environment for the documentation of the SkiNet project
name: skinet-docs
channels:
  - defaults
  - conda-forge
dependencies:
  - sphinx
  - furo
  - myst-parser
  - sphinx-togglebutton