GENERAL_CONFIG:
  experiment_type: "segmentation"
  model: "UNET2D_MODEL"
  dataset: "PH2_DATASET"
DATA_CONFIG:
  local_data_root:
  azure_data: True
  azure_blob_mount_point: "/mnt/data/"
  crop_size: [256, 256]
  split_random_seed: 100
TRANSFORM_CONFIG:
  seed_value: 100
  crop:
    crop_apply: True
    crop_type: "random_resized_crop"
    size: [512, 512]
    scale: [0.8, 1.0]
  spatial_augmentation:
    square_symmetry_apply: True
    square_symmetry_p: 0.5
    affine_apply: True
    affine_scale: [0.5, 1.0]
    affine_translate_percent: {"x": [-0.05, 0.05], "y": [-0.05, 0.05]}
    affine_rotate: [-45, 45]
    affine_shear: {"x": [-15, 15], "y": [-15, 15]}
    perspective_apply: True
    perspective_scale: [0.05, 0.1]
    perspective_p: 0.2
  photometric_augmentation:
    color_jitter_apply: True
    color_jitter_brightness: 0.2
    color_jitter_contrast: 0.2
    color_jitter_saturation: 0.0
    color_jitter_hue: 0.0
    color_jitter_p: 0.5
MODEL_CONFIG:

TRAIN_CONFIG:
  log_dir: "lightning_logs"
  experiment_name: "unet2d_ph2_noaggregate"
  run_test_after_fit: false
  test_on_val_split: false
  batch_size: 8
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2
  loss_name: "bce_dice"
  optimizer_name: "adamw"
  lr: 1e-4
  weight_decay: 1e-4
  seed: 100
  deterministic: true
  max_epochs: 100
  accelerator: "cpu"
  devices: 1
  precision: "16-mixed"
  log_every_n_steps: 1
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  use_mlflow_logger: true
  use_litlogger_logger: true
  use_early_stopping: true
  use_checkpoint: true
  early_stopping_config:
    monitor: "val_best_dice_at_threshold"
    mode: "max"
    min_delta: 0.005
    patience: 15
    strict: true
    check_finite: true
    stopping_threshold:
    divergence_threshold:
  checkpoint_config:
    monitor: "val_best_dice_at_threshold"
    mode: "max"
    save_top_k: 3
    save_last: true
    filename: "epoch{epoch:03d}"
  litlogger_config:
    teamspace: "l-pkliui"
    log_model: false
    save_logs: false
    checkpoint_name:
  mlflow_config:
    fallback_to_local_mlflow: false
    tracking_uri: "http://127.0.0.1:5000" # OK
    log_model: "all"
    log_model_summary: true
  lr_scheduler_config:
    monitor: "val_best_dice_at_threshold"
    mode: "max"
    patience: 8
    factor: 0.5
