GENERAL_CONFIG:
  experiment_type: "segmentation"
  model: "UNET2D_MODEL"
  dataset: "PH2_DATASET"
DATA_CONFIG:
  local_data_root:
  azure_data: True
  azure_blob_mount_point: "mnt/data/"
MODEL_CONFIG:
TRAIN_CONFIG:
