# dev azure settings
AZURE_TENANT_ID: '69414ce3-7590-45c7-ac2b-67dc8241e2da'
AZURE_CLIENT_ID: '722cc092-3573-4880-9c46-7c4465d1ddcb'
SUBSCRIPTION_ID: 'ca38a29f-5476-45bb-9672-fe12e0e81b20'
RESOURCE_GROUP: 'pkliui-rg'
WORKSPACE_NAME: 'skinet-ws'
DATASTORE_NAME: 'skinetdatastore'
PATH_ON_DATASTORE:
  PH2_DATASET : 'PH2DATA/'