name: Workflow to update documentation index.html each time the code in docs/source changes

on:
  push:
    branches:
      - documentation

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: skinet-docs
          environment-file: environment_docs.yaml
          auto-activate-base: false

      - name: Sphinx build
        shell: bash -l {0}  # Ensures Conda is properly activated
        run: |
          sphinx-build -b html docs/source/ docs/build/html
          touch docs/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/documentation' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
